<a href="https://colab.research.google.com/github/adinsa1/Data110/blob/main/MultipleregAssefa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [94]:



# import Packages
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [103]:
#
df = pd.read_csv('https://raw.githubusercontent.com/adinsa1/Data110/main/Dataset/life_exp_kaggle_full.csv')
df.head()

,Country Name,Country Code,Region,IncomeGroup,Year,Life Expectancy World Bank,Prevelance of Undernourishment,CO2,Health Expenditure %,Education Expenditure %,Unemployment,Corruption,Sanitation,Injuries,Communicable,NonCommunicable
0,Afghanistan,AFG,South Asia,Low income,2001,56.308,47.8,730.0,NaN,NaN,10.809000,NaN,NaN,2179727.10,9689193.70,5795426.38
1,Angola,AGO,Sub-Saharan Africa,Lower middle income,2001,47.059,67.5,15960.0,4.483516,NaN,4.004000,NaN,NaN,1392080.71,11190210.53,2663516.34
2,Albania,ALB,Europe & Central Asia,Upper middle income,2001,74.288,4.9,3230.0,7.139524,3.4587,18.575001,NaN,40.520895,117081.67,140894.78,532324.75
3,Andorra,AND,Europe & Central Asia,High income,2001,NaN,NaN,520.0,5.865939,NaN,NaN,NaN,21.788660,1697.99,695.56,13636.64
4,United Arab Emirates,ARE,Middle East & North Africa,High income,2001,74.544,2.8,97200.0,2.484370,NaN,2.493000,NaN,NaN,144678.14,65271.91,481740.70

In [96]:
#
df.isnull().sum()

Country Name                         0
Country Code                         0
Region                               0
IncomeGroup                          0
Year                                 0
Life Expectancy World Bank         188
Prevelance of Undernourishment     684
CO2                                152
Health Expenditure %               180
Education Expenditure %           1090
Unemployment                       304
Corruption                        2331
Sanitation                        1247
Injuries                             0
Communicable                         0
NonCommunicable                      0
dtype: int64

In [104]:
#
df.dropna()

,Country Name,Country Code,Region,IncomeGroup,Year,Life Expectancy World Bank,Prevelance of Undernourishment,CO2,Health Expenditure %,Education Expenditure %,Unemployment,Corruption,Sanitation,Injuries,Communicable,NonCommunicable
698,Albania,ALB,Europe & Central Asia,Upper middle income,2005,75.228,8.9,4030.000210,6.335542,3.281550,15.970000,3.0,41.875655,94241.87,99241.18,568930.66
702,Armenia,ARM,Europe & Central Asia,Upper middle income,2005,72.626,12.3,4460.000038,5.861883,2.712030,10.203000,2.5,46.657125,92659.79,105444.38,793047.77
707,Azerbaijan,AZE,Europe & Central Asia,Upper middle income,2005,68.747,4.8,30040.000920,2.261077,2.974620,7.260000,2.5,23.121008,240229.35,826520.96,2003781.90
724,Central African Republic,CAF,Sub-Saharan Africa,Low income,2005,44.744,39.6,219.999999,4.367321,1.652220,5.695000,2.5,19.090005,310132.64,3766393.86,805165.65
737,Djibouti,DJI,Middle East & North Africa,Lower middle income,2005,57.991,31.3,430.000007,3.224672,8.365890,27.719999,2.5,25.705269,28409.67,310769.59,115615.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3279,Sao Tome and Principe,STP,Sub-Saharan Africa,Lower middle income,2019,70.385,13.0,150.000006,5.529762,5.921550,14.144000,3.5,33.535911,4293.10,16170.29,33337.54
3285,Chad,TCD,Sub-Saharan Africa,Low income,2019,54.239,31.7,2250.000000,4.353631,2.372460,1.123000,2.5,9.951136,626720.09,8496915.83,2459705.38
3286,Togo,TGO,Sub-Saharan Africa,Low income,2019,61.042,20.1,2369.999886,5.726069,4.069143,3.719000,3.0,9.103834,246081.26,1992666.23,1190315.76
3294,Tanzania,TZA,Sub-Saharan Africa,Lower middle income,2019,65.456,23.4,12449.999810,3.827693,3.596836,2.222000,3.0,26.238278,1478236.12,13341065.72,8469064.37
3302,Samoa,WSM,East Asia & Pacific,Lower middle income,2019,73.321,4.4,300.000012,6.363094,4.706250,8.406000,4.0,47.698788,6652.84,9095.19,43798.62

In [106]:

df=df.drop['CO2','Prevelance of Undernourishment','Health Expenditure %','Education Expenditure %','Unemployment', 'Corruption','Sanitation','Injuries']

KeyError: ('CO2', 'Prevelance of Undernourishment', 'Health Expenditure %', 'Education Expenditure %', 'Unemployment', 'Corruption', 'Sanitation', 'Injuries')

In [101]:
y=df['Life Expectancy World Bank']

In [105]:

#
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3,random_state=0)

ValueError: Found input variables with inconsistent numbers of samples: [286, 3306]

In [ ]:
#
from sklearn.linear_model import LinearRegression
lr = LinearRegression()